sudo: required

os: osx
language: node_js
node_js:
  - "10"

branches:
  only:
  - development

before_install:
  - rvm install 2.5.1
  - yarn global add gulp-cli

cache:
  yarn: true
  bundler: true
  directories:
    - /node_modules/
    - /aws-caches/

install:
  - yarn install --production=false --ignore-optional

jobs:
  include:
    - stage: staging-job
      if: branch = development OR branch = staging
      script: gulp staging
    - stage: publishing-job
      if: branch = publishing
      script: gulp publish
