sudo: required

language: node
node_js:
  - "10"

services:
  - docker

branches:
  only:
  - development

before_install:
  - docker pull blundin/brianlundin_com:latest
  - docker run -d blundin/brianlundin_com /bin/sh -c "yarn add gulp-cli; gulp publish;"

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
