sudo: required

os: osx
language: node_js
node_js:
  - "10"

before_install:
  - rvm install 2.5.1
  - yarn global add gulp-cli

cache:
  yarn: true

install:
  - yarn install --production=false --ignore-optional
  - bundle install

script:
  - gulp staging
