sudo: required

os: osx
language: node_js
node_js:
  - "10"

branches:
  only:
  - development
  - master

before_install:
  - yarn global add gulp-cli

after_install:
  - bundle show --paths

cache:
  yarn: true
  bundler: true

install:
  - yarn install --production=false --ignore-optional
  - bundle install

jobs:
  include:
    - stage: staging-job
      if: branch = development OR branch = staging
      script: gulp staging
    - stage: publishing-job
      if: branch = master
      script: gulp publish
