sudo: required

os: osx
language: node_js
node_js:
  - "10"

branches:
  only:
  - development
  - staging
  - issues
  - master

cache:
  yarn: true
  bundler: true
  directories:
    - /Users/travis/.rvm/
    - $HOME/src/.cache

before_install:
  - yarn global add gulp-cli

install:
  - yarn install --production=false --ignore-optional
  - bundle install

jobs:
  include:
    - stage: staging-job
      if: branch = staging OR branch = issues
      script: gulp staging
    - stage: development-job
      if: branch = development
      script: gulp staging
    - stage: publishing-job
      if: branch = master
      script: gulp publish
