sudo: required

language: node

node_js:
  - 10.9.0

before_install:
  - rvm install 2.5.1
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true

install:
  - yarn global add gulp-cli
  - yarn install --production=false --ignore-optional
  - bundle install

script:
  - gulp staging
