# Site settings
title: Brian Lundin
email: brian.lundin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Brian Lundin is the Lead Writer & Story Team Producer at The Austin Stone Community Church. Brian is a storyteller, writer and geek who is passsionate about sharing stories of gospel transformation.

# Settings for the site
baseurl: ""
url: "https://brianlundin.com"
cdn_url: "" # If this is set the site will directly use the CDN URL for all assets
twitter_username: blundin
github_username:  blundin

# Build settings
source: src
destination: public
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /blog/:title:output_ext
sass:
  load_paths:
    - "../node_modules/bootstrap/scss"
    - "_sass"
  style: compressed
safe: false

# Pagination options
pagination:
  trail:
    before: 3 # The number of links before the current page
    after: 3  # The number of links after the current page
  enabled: true
  debug: false
  per_page: 5
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    layouts:
      - 'tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/:tag'

# Jekyll stuff
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

# Exclude from processing
exclude:
  - js
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - yarn.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .ruby-version
  - .ruby-gemset
