# Site settings
title: brianlundin.com

email: brian.lundin@gmail.com
twitter_username: blundin
github_username:  blundin

description: > # this means to ignore newlines until "baseurl:"
  Brian Lundin is a storyteller, writer, and geek who lives in Austin, TX. He is passionate about Jesus, literature, writing, and telling stories of redemption in the lives of God’s people.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://brianlundin.com" # the base hostname & protocol for your site
cdn: "https://brianlundin.com" # comment this line out for the site to generate local URLs for CDN-hosted assests

markdown_ext: "markdown,mkdown,mkdn,mkd,md"


paginate: 7
paginate_path: "page:num"
permalink: blog/:title.html

exclude: ["node_modules",
          "Gruntfile.js",
          "bower.json",
          "package.json",
          "publish.sh",
          "README.md",
          "*.sublime-*",
          "Gemfile",
          "Gemfile.lock",
          "LICENSE.md",
          "bower_components"]

plugins: ["jekyll-redirect-from", "jekyll-paginate", "jekyll/footnotes"]
