# Site settings
title: Brian Lundin
email: brian.lundin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Brian Lundin is the Lead Writer & Story Team Producer at The Austin Stone Community Church. Brian is a storyteller, writer and geek who is passsionate about sharing stories of gospel transformation.
baseurl: ""
url: "https://brianlundin.com"
twitter_username: blundin
github_username:  blundin

# Build settings
source: src
destination: public
markdown: kramdown
sass:
  load_paths:
    - "../node_modules/bootstrap/scss"
    - "_sass"
  style: compressed
safe: false

# Jekyll stuff
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - yarn.lock
  # - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
