image: starefossen/ruby-node:latest

pipelines:
  branches:
    publishing:
      - step:
          script:
            - yarn global add gulp-cli
            - yarn install --production=false
            - bundle install
            - gulp publish
