image:
  name: blundin/brianlundin_com:latest
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL
pipelines:
  branches:
    publishing:
      - step:
          script:
            - export PRODUCTION_BUCKET=$PRODUCTION_BUCKET
            - export PRODUCTION_ACCESS_KEY=$PRODUCTION_ACCESS_KEY
            - export PRODUCTION_SECRET_ACCESS_KEY=$PRODUCTION_SECRET_ACCESS_KEY
            - export AWS_REGION=$AWS_REGION
            - gulp publish
    staging:
      - step:
          script:
            - export STAGING_BUCKET=$STAGING_BUCKET
            - export STAGING_ACCESS_KEY=$STAGING_ACCESS_KEY
            - export STAGING_SECRET_ACCESS_KEY=$STAGING_SECRET_ACCESS_KEY
            - export AWS_REGION=$AWS_REGION
            - gulp staging
